app/gaia/gaia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('timeline.urls')),
    path('', include('place.urls')),
]

app/gaia/place/urls.py
from django.urls import path

from .views import PlaceListView, PlaceUpdateView, PlaceCreateView, PlaceDeleteView, PlaceDetailView
from .views import EventListView, EventUpdateView, EventCreateView, EventDeleteView, EventDetailView

app_name = 'place'

urlpatterns = [
    path('place/all/', PlaceListView.as_view(), name='place-list'),
    path('place/<int:pk>', PlaceDetailView.as_view(), name='place-detail'),
    path('place/create/', PlaceCreateView.as_view(), name='place-create'),
    path('place/<int:pk>/update/', PlaceUpdateView.as_view(), name='place-update'),
    path('place/<int:pk>/delete/', PlaceDeleteView.as_view(), name='place-delete'),
    path('event/all/', EventListView.as_view(), name='event-list'),
    path('event/<int:pk>', EventDetailView.as_view(), name='event-detail'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),
    path('event/<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
]

app/gaia/project/urls.py
from django.urls import path

from .views import Homepage
from .views import Dashboard
from .views import ProjectListView, ProjectUpdateView, ProjectCreateView, ProjectDeleteView, ProjectDetailView
from .views import ReferenceListView, ReferenceUpdateView, ReferenceCreateView, ReferenceDeleteView, ReferenceDetailView

app_name = 'project'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('project/', Dashboard.as_view(), name='dashboard'),
    path('project/all/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project-detail'),
    path('project/create/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('reference/all/', ReferenceListView.as_view(), name='reference-list'),
    path('reference/<int:pk>', ReferenceDetailView.as_view(), name='reference-detail'),
    path('reference/create/', ReferenceCreateView.as_view(), name='reference-create'),
    path('reference/<int:pk>/update/', ReferenceUpdateView.as_view(), name='reference-update'),
    path('reference/<int:pk>/delete/', ReferenceDeleteView.as_view(), name='reference-delete'),
]

app/gaia/timeline/urls.py
from django.urls import path

from .views import TimelineListView, TimelineUpdateView, TimelineCreateView, TimelineDeleteView, TimelineDetailView

app_name = 'timeline'

urlpatterns = [
    path('timeline/all/', TimelineListView.as_view(), name='timeline-list'),
    path('timeline/<int:pk>', TimelineDetailView.as_view(), name='timeline-detail'),
    path('timeline/create/', TimelineCreateView.as_view(), name='timeline-create'),
    path('timeline/<int:pk>/update/', TimelineUpdateView.as_view(), name='timeline-update'),
    path('timeline/<int:pk>/delete/', TimelineDeleteView.as_view(), name='timeline-delete'),
]

app/gaia/base/models.py
from django.db import models


class BaseModel(models.Model):
    """Abstract class to contain meta data"""

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

app/gaia/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Gaia | Create your universe</title>
  </head>
  <body>

    {% include 'navbar.html' %}

    {% include 'messages.html' %}

    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

app/gaia/templates/form.html
{% load widget_tweaks %}

<form method="POST">

    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field. %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

app/gaia/templates/messages.html
{% for message in messages %}

<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>

{% endfor %}

app/gaia/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'project:homepage' %}"><strong>GAIA</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'project:project-list' %}">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'project:reference-list' %}">References</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'timeline:timeline-list' %}">Timelines</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'place:place-list' %}">Places</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'place:event-list' %}">Events</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Guest
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>