app/gaia/gaia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('timeline.urls')),
    path('', include('place.urls')),
]

app/gaia/project/urls.py
from django.urls import path

from .views import Homepage
from .views import Dashboard
from .views import ProjectListView, ProjectUpdateView, ProjectCreateView, ProjectDeleteView, ProjectDetailView
from .views import ReferenceListView, ReferenceUpdateView, ReferenceCreateView, ReferenceDeleteView, ReferenceDetailView

app_name = 'project'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('project/', Dashboard.as_view(), name='dashboard'),
    path('project/all/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project-detail'),
    path('project/create/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('reference/all/', ReferenceListView.as_view(), name='reference-list'),
    path('reference/<int:pk>', ReferenceDetailView.as_view(), name='reference-detail'),
    path('reference/create/', ReferenceCreateView.as_view(), name='reference-create'),
    path('reference/<int:pk>/update/', ReferenceUpdateView.as_view(), name='reference-update'),
    path('reference/<int:pk>/delete/', ReferenceDeleteView.as_view(), name='reference-delete'),
]

app/gaia/project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from base.models import BaseModel


class Reference(BaseModel):
    """
    A reference is a short note on any term introduced in any project
    """
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("project:reference-detail", kwargs={"pk": self.pk})


class Project(BaseModel):
    """
    A Gaia project is the leading entity that a user can create.
    All elements will be associated with a project.
    """

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=2000, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("project:project-detail", kwargs={"pk": self.pk})

app/gaia/project/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .models import Project
from .models import Reference


class Homepage(TemplateView):
    """
    Main Page
    """
    template_name = "project/homepage.html"


class Dashboard(TemplateView):
    """
    Dashboard for a user
    """
    template_name = "project/dashboard.html"


class ProjectListView(ListView):
    """
    Listing all the project
    """
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectDetailView(DetailView):
    """
    Details of a project
    """
    template_name = 'project/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectCreateView(SuccessMessageMixin, CreateView):
    """
    Creating a new project
    """
    template_name = 'project/project_create.html'
    model = Project
    fields = ('title', 'description', 'user')
    success_message = 'New project created!'


class ProjectUpdateView(SuccessMessageMixin, UpdateView):
    """
    Updating a new project
    """
    template_name = 'project/project_update.html'
    model = Project
    fields = ('description',)
    success_message = 'Project updated!'


class ProjectDeleteView(DeleteView):
    """
    Deleting an existing project
    """
    template_name = 'project/project_detail.html'
    model = Project
    success_url = reverse_lazy('project:project-list')


class ReferenceListView(ListView):
    """
    Listing all the references
    """
    template_name = 'project/reference_list.html'
    model = Reference
    context_object_name = 'references'


class ReferenceDetailView(DetailView):
    """
    Details of a reference
    """
    template_name = 'project/reference_detail.html'
    model = Reference
    context_object_name = 'reference'


class ReferenceCreateView(SuccessMessageMixin, CreateView):
    """
    Creating a new reference
    """
    template_name = 'project/reference_create.html'
    model = Reference
    fields = ('title', 'description')
    success_message = 'New reference created!'


class ReferenceUpdateView(SuccessMessageMixin, UpdateView):
    """
    Updating a new reference
    """
    template_name = 'project/reference_update.html'
    model = Reference
    fields = ('description',)
    success_message = 'Reference updated!'


class ReferenceDeleteView(DeleteView):
    """
    Deleting an existing reference
    """
    template_name = 'project/reference_detail.html'
    model = Reference
    success_url = reverse_lazy('project:reference-list')

app/gaia/templates/project/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">

    <div class="row">
        <div class="col-12">
            <div class="jumbotron">
            <h1 class="display-4">Dashboard</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-3">
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action">Timelines</a>
                <a href="#" class="list-group-item list-group-item-action">Places</a>
                <a href="#" class="list-group-item list-group-item-action">Characters</a>
                <a href="#" class="list-group-item list-group-item-action">Factions</a>
                <a href="#" class="list-group-item list-group-item-action">Events</a>
                <a href="#" class="list-group-item list-group-item-action">Tools</a>
                <a href="#" class="list-group-item list-group-item-action">Weapons</a>
                <a href="#" class="list-group-item list-group-item-action">Currency</a>
                <a href="#" class="list-group-item list-group-item-action">Resources</a>
                <a href="#" class="list-group-item list-group-item-action">References</a>
            </div>
        </div>
        <div class="col-9">
        </div>
    </div>

</div>

{% endblock content %}

app/gaia/templates/project/homepage.html
{% extends 'base.html' %}

{% block content %}

<div class="container py-4">
    <div class="jumbotron">
    <h1 class="display-4">Welcome to Gaia!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/project_create.html
{% extends 'base.html' %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Create new project</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/project_detail.html
{% extends 'base.html' %}

{% include 'messages.html' %}

{% block content %}

<div class="container-fluid my-2">
  <div class="row">
    <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>{{ project.title }}</h3>
  </div>
  <div class="card-body">
    <p>{{ project.description }}</p>
  </div>
  <div class="card-footer">
    <a href="{% url 'project:project-update' pk=project.pk %}" class="btn btn-primary">Edit</a>
    <button class="btn btn-primary" data-toggle="modal" data-target="#deleteConfirmationModalCenter">Delete</button>
    <br>
    <br>
    <a href="{% url 'project:project-list' %}">Back to project list</a>
  </div>
</div>

    </div>
  </div>
</div>

<div class="modal fade" id="deleteConfirmationModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        The project along with all the associated details will be lost.
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'project:project-delete' pk=project.pk %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/gaia/templates/project/project_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Total project(s) : {{ projects.count }}</h3>
    <hr>
    <a href="{% url 'project:project-create' %}" class="btn btn-primary">New project</a>
  </div>
  <div class="card-body">
    <div class="list-group">
      {% for project in projects %}
        <a href="{% url 'project:project-detail' pk=project.pk %}" class="list-group-item list-group-item-action">{{ project.title }}</a>
      {% empty %}
        No projects right now!
      {% endfor %}
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/project_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Update project</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/reference_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Create new reference</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/reference_detail.html
{% extends 'base.html' %}

{% include 'messages.html' %}

{% block content %}

<div class="container-fluid my-2">
  <div class="row">
    <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>{{ reference.title }}</h3>
  </div>
  <div class="card-body">
    <p>{{ reference.description }}</p>
  </div>
  <div class="card-footer">
    <a href="{% url 'project:reference-update' pk=reference.pk %}" class="btn btn-primary">Edit</a>
    <button class="btn btn-primary" data-toggle="modal" data-target="#deleteConfirmationModalCenter">Delete</button>
    <br>
    <br>
    <a href="{% url 'project:reference-list' %}">Back to reference list</a>
  </div>
</div>

    </div>
  </div>
</div>

<div class="modal fade" id="deleteConfirmationModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This will delete the reference.
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'project:reference-delete' pk=reference.pk %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/gaia/templates/project/reference_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Total reference(s) : {{ references.count }}</h3>
    <hr>
    <a href="{% url 'project:reference-create' %}" class="btn btn-primary">New reference</a>
  </div>
  <div class="card-body">
    <div class="list-group">
      {% for reference in references %}
        <a href="{% url 'project:reference-detail' pk=reference.pk %}" class="list-group-item list-group-item-action">{{ reference.title }}</a>
      {% empty %}
        No reference(s) right now!
      {% endfor %}
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/project/reference_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Update reference</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}