app/gaia/gaia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('timeline.urls')),
    path('', include('place.urls')),
]

app/gaia/place/urls.py
from django.urls import path

from .views import PlaceListView, PlaceUpdateView, PlaceCreateView, PlaceDeleteView, PlaceDetailView
from .views import EventListView, EventUpdateView, EventCreateView, EventDeleteView, EventDetailView

app_name = 'place'

urlpatterns = [
    path('place/all/', PlaceListView.as_view(), name='place-list'),
    path('place/<int:pk>', PlaceDetailView.as_view(), name='place-detail'),
    path('place/create/', PlaceCreateView.as_view(), name='place-create'),
    path('place/<int:pk>/update/', PlaceUpdateView.as_view(), name='place-update'),
    path('place/<int:pk>/delete/', PlaceDeleteView.as_view(), name='place-delete'),
    path('event/all/', EventListView.as_view(), name='event-list'),
    path('event/<int:pk>', EventDetailView.as_view(), name='event-detail'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),
    path('event/<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
]

app/gaia/timeline/urls.py
from django.urls import path

from .views import TimelineListView, TimelineUpdateView, TimelineCreateView, TimelineDeleteView, TimelineDetailView

app_name = 'timeline'

urlpatterns = [
    path('timeline/all/', TimelineListView.as_view(), name='timeline-list'),
    path('timeline/<int:pk>', TimelineDetailView.as_view(), name='timeline-detail'),
    path('timeline/create/', TimelineCreateView.as_view(), name='timeline-create'),
    path('timeline/<int:pk>/update/', TimelineUpdateView.as_view(), name='timeline-update'),
    path('timeline/<int:pk>/delete/', TimelineDeleteView.as_view(), name='timeline-delete'),
]

app/gaia/place/models.py
from django.db import models
from django.urls import reverse

from base.models import BaseModel
from timeline.models import Timeline


class Place(BaseModel):
    """
    A place is a location in space where characters can live and events can happen.
    One place can have many other places.
    A place is the most important entity in a project as plots can revolve around places.
    """

    name = models.CharField(max_length=200, help_text="E.g. Earth, Dimension 616, Delhi etc.")
    description = models.TextField(help_text="Some description of the place.")

    domain = models.ForeignKey('self', on_delete=models.CASCADE, related_name='places_within', null=True, blank=True)
    timeline = models.ForeignKey(Timeline, on_delete=models.CASCADE, related_name='places')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("place:place-detail", kwargs={"pk": self.pk})


class Event(BaseModel):
    """
    A notable event that has taken place in a timeline.
    An event can be associated with any character or place.
    """

    heading = models.CharField(max_length=500, help_text="E.g. First World War, Battle of Bastards etc.")
    description = models.TextField(help_text="Details of the event.")

    time_started = models.CharField(max_length=20, help_text="E.g. 1914, 320 BC etc.")
    time_ended = models.CharField(max_length=20, help_text="E.g. 1918, Present etc.")

    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name="events")

    def __str__(self):
        return f"{self.heading} : Started in {self.time_started} - Ended in {self.time_ended}"

    def get_absolute_url(self):
        return reverse("place:event-detail", kwargs={"pk": self.pk})

app/gaia/place/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .models import Place
from .models import Event


class PlaceListView(ListView):
    """
    Listing all the place
    """
    template_name = 'place/place_list.html'
    model = Place
    context_object_name = 'places'


class PlaceDetailView(DetailView):
    """
    Details of a place
    """
    template_name = 'place/place_detail.html'
    model = Place
    context_object_name = 'place'


class PlaceCreateView(SuccessMessageMixin, CreateView):
    """
    Creating a new place
    """
    template_name = 'place/place_create.html'
    model = Place
    fields = ('name', 'description', 'domain', 'timeline',)
    success_message = 'New place created!'


class PlaceUpdateView(SuccessMessageMixin, UpdateView):
    """
    Updating a new place
    """
    template_name = 'place/place_update.html'
    model = Place
    fields = ('description', 'domain', 'timeline',)
    success_message = 'Place updated!'


class PlaceDeleteView(DeleteView):
    """
    Deleting an existing place
    """
    template_name = 'place/place_detail.html'
    model = Place
    success_url = reverse_lazy('place:place-list')


class EventListView(ListView):
    """
    Listing all the event
    """
    template_name = 'place/event_list.html'
    model = Event
    context_object_name = 'events'


class EventDetailView(DetailView):
    """
    Details of a event
    """
    template_name = 'place/event_detail.html'
    model = Event
    context_object_name = 'event'


class EventCreateView(SuccessMessageMixin, CreateView):
    """
    Creating a new event
    """
    template_name = 'place/event_create.html'
    model = Event
    fields = ('heading', 'description', 'time_started', 'time_ended', 'place',)
    success_message = 'New event created!'


class EventUpdateView(SuccessMessageMixin, UpdateView):
    """
    Updating a new event
    """
    template_name = 'place/event_update.html'
    model = Event
    fields = ('description', 'time_started', 'time_ended', 'place',)
    success_message = 'Event updated!'


class EventDeleteView(DeleteView):
    """
    Deleting an existing event
    """
    template_name = 'place/event_detail.html'
    model = Event
    success_url = reverse_lazy('event:event-list')

app/gaia/templates/place/event_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Create new event</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/place/event_detail.html
{% extends 'base.html' %}

{% include 'messages.html' %}

{% block content %}

<div class="container-fluid my-2">
  <div class="row">
    <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>{{ event.heading }}</h3>
  </div>
  <div class="card-body">
    <p class="lead">{{ event.heading }} took place at <a href="{% url 'place:place-detail' pk=event.place.pk %}">{{ event.place.name }}</a></p>
    <p class="lead">Started : {{ event.time_started }}</p>
    <p class="lead">Ended : {{ event.time_ended }}</p>
    <p>{{ place.description }}</p>
  </div>
  <div class="card-footer">
    <a href="{% url 'place:event-update' pk=event.pk %}" class="btn btn-primary">Edit</a>
    <button class="btn btn-primary" data-toggle="modal" data-target="#deleteConfirmationModalCenter">Delete</button>
    <br>
    <br>
    <a href="{% url 'place:event-list' %}">Back to event list</a>
  </div>
</div>


    </div>
  </div>
</div>

<div class="modal fade" id="deleteConfirmationModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This will delete the event.
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'place:event-delete' pk=event.pk %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/gaia/templates/place/event_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Total event(s) : {{ events.count }}</h3>
    <hr>
    <a href="{% url 'place:event-create' %}" class="btn btn-primary">New event</a>
  </div>
  <div class="card-body">
    <div class="list-group">
      {% for event in events %}
        <a href="{% url 'place:event-detail' pk=event.pk %}" class="list-group-item list-group-item-action">{{ event.heading }}</a>
      {% empty %}
        No event(s) right now!
      {% endfor %}
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/place/event_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Update event</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/place/place_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Create new place</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/place/place_detail.html
{% extends 'base.html' %}

{% include 'messages.html' %}

{% block content %}

<div class="container-fluid my-2">
  <div class="row">
    <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>{{ place.name }}</h3>
  </div>
  <div class="card-body">
    <p>{{ place.description }}</p>
    Domain : 
    {% if not place.domain  %}
      No Domain
    {% else %}
      <a href="{% url 'place:place-detail' pk=place.domain.pk %}">{{ place.domain.name }}</a>
    {% endif %}
    <br>
    Timeline : <a href="{% url 'timeline:timeline-detail' pk=place.timeline.pk %}">{{ place.timeline.era }}</a>
  </div>
  <div class="card-footer">
    <a href="{% url 'place:place-update' pk=place.pk %}" class="btn btn-primary">Edit</a>
    <button class="btn btn-primary" data-toggle="modal" data-target="#deleteConfirmationModalCenter">Delete</button>
    <br>
    <br>
    <a href="{% url 'place:place-list' %}">Back to place list</a>
  </div>
</div>

    </div>
  </div>
</div>

<div class="modal fade" id="deleteConfirmationModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This will delete the place.
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'place:place-delete' pk=place.pk %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/gaia/templates/place/place_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Total place(s) : {{ places.count }}</h3>
    <hr>
    <a href="{% url 'place:place-create' %}" class="btn btn-primary">New place</a>
  </div>
  <div class="card-body">
    <div class="list-group">
      {% for place in places %}
        <a href="{% url 'place:place-detail' pk=place.pk %}" class="list-group-item list-group-item-action">{{ place.name }}</a>
      {% empty %}
        No place(s) right now!
      {% endfor %}
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/place/place_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Update place</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}