app/gaia/gaia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('timeline.urls')),
    path('', include('place.urls')),
]

app/gaia/timeline/urls.py
from django.urls import path

from .views import TimelineListView, TimelineUpdateView, TimelineCreateView, TimelineDeleteView, TimelineDetailView

app_name = 'timeline'

urlpatterns = [
    path('timeline/all/', TimelineListView.as_view(), name='timeline-list'),
    path('timeline/<int:pk>', TimelineDetailView.as_view(), name='timeline-detail'),
    path('timeline/create/', TimelineCreateView.as_view(), name='timeline-create'),
    path('timeline/<int:pk>/update/', TimelineUpdateView.as_view(), name='timeline-update'),
    path('timeline/<int:pk>/delete/', TimelineDeleteView.as_view(), name='timeline-delete'),
]

app/gaia/timeline/models.py
from django.db import models
from django.urls import reverse

from base.models import BaseModel
from project.models import Project


class Timeline(BaseModel):
    """
    A timeline is a starting point for any Project.
    One project can have many timelines, and all the smaller entities are part of the timeline.
    """

    era = models.CharField(max_length=200, help_text="E.g. Jurrassic, Stone Age, Satayuga etc.")
    start_period = models.BigIntegerField(help_text="E.g. 1914, 2000, 420 etc.")
    end_period = models.BigIntegerField(help_text="E.g. 1914, 2000, 420 etc.")
    label = models.CharField(max_length=4, help_text="E.g. BC, AD, BCE etc.")

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="timelines")

    def __str__(self):
        return f"{self.era} : {self.start_period} - {self.end_period} {self.label}"

    def get_absolute_url(self):
        return reverse("timeline:timeline-detail", kwargs={"pk": self.pk})

app/gaia/timeline/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .models import Timeline


class TimelineListView(ListView):
    """
    Listing all the timeline
    """
    template_name = 'timeline/timeline_list.html'
    model = Timeline
    context_object_name = 'timelines'


class TimelineDetailView(DetailView):
    """
    Details of a timeline
    """
    template_name = 'timeline/timeline_detail.html'
    model = Timeline
    context_object_name = 'timeline'


class TimelineCreateView(SuccessMessageMixin, CreateView):
    """
    Creating a new timeline
    """
    template_name = 'timeline/timeline_create.html'
    model = Timeline
    fields = ('era', 'start_period', 'end_period', 'label', 'project')
    success_message = 'New timeline created!'


class TimelineUpdateView(SuccessMessageMixin, UpdateView):
    """
    Updating a new timeline
    """
    template_name = 'timeline/timeline_update.html'
    model = Timeline
    fields = ('start_period', 'end_period', 'label',)
    success_message = 'Timeline updated!'


class TimelineDeleteView(DeleteView):
    """
    Deleting an existing timeline
    """
    template_name = 'timeline/timeline_detail.html'
    model = Timeline
    success_url = reverse_lazy('timeline:timeline-list')

app/gaia/templates/timeline/timeline_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Create new timeline</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/timeline/timeline_detail.html
{% extends 'base.html' %}

{% include 'messages.html' %}

{% block content %}

<div class="container-fluid my-2">
  <div class="row">
    <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>{{ timeline.era }}</h3>
  </div>
  <div class="card-body">
    <h5>{{ timeline.project.title }}</h5>
    {{ timeline.start_period }} - {{ timeline.end_period }} {{ timeline.label }}
  </div>
  <div class="card-footer">
    <a href="{% url 'timeline:timeline-update' pk=timeline.pk %}" class="btn btn-primary">Edit</a>
    <button class="btn btn-primary" data-toggle="modal" data-target="#deleteConfirmationModalCenter">Delete</button>
    <br>
    <br>
    <a href="{% url 'timeline:timeline-list' %}">Back to timeline list</a>
  </div>
</div>

    </div>
  </div>
</div>

<div class="modal fade" id="deleteConfirmationModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This will delete the timeline.
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'timeline:timeline-delete' pk=timeline.pk %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/gaia/templates/timeline/timeline_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Total timeline(s) : {{ timelines.count }}</h3>
    <hr>
    <a href="{% url 'timeline:timeline-create' %}" class="btn btn-primary">New timeline</a>
  </div>
  <div class="card-body">
    <div class="list-group">
      {% for timeline in timelines %}
        <a href="{% url 'timeline:timeline-detail' pk=timeline.pk %}" class="list-group-item list-group-item-action">{{ timeline.era }}</a>
      {% empty %}
        No timeline(s) right now!
      {% endfor %}
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}

app/gaia/templates/timeline/timeline_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'messages.html' %}

<div class="container-fluid my-2">
    <div class="row">
        <div class="col-12">

<div class="card shadow mb-5 bg-white rounded">
  <div class="card-header">
    <h3>Update timeline</h3>
  </div>
  <div class="card-body">
    {% include 'form.html' %}
  </div>
</div>

        </div>
    </div>
</div>

{% endblock content %}